# Resets the develop branch to match the main branch.
# 
# In typical situations, you would want to run this on a schedule such as the following which will 
# trigger the workflow at midnight every Sunday:
# on:
#   schedule:
#     - cron: "0 0 * * SUN"
#
# Refer to the README for details on the WORKFLOW parameters.
#

name: Reset develop branch to match main

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string
      DEVELOPMENT_BRANCH:
        required: false
        type: string
        default: develop
      MAIN_BRANCH:
        required: false
        type: string
        default: main
    secrets:
      WORKFLOW_APP_ID:
        required: true
      WORKFLOW_PRIVATE_KEY:
        required: true

jobs:
  reset-dev-to-main:
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.WORKFLOW_APP_ID }}
          private_key: ${{ secrets.WORKFLOW_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Reset development branch to match main branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout ${{ inputs.DEVELOPMENT_BRANCH }}
          git reset --hard origin/${{ inputs.MAIN_BRANCH }}
          git push --force
